export const teamMembers = [
  {
    name: "Aarab Nishchal",
    roll_num: "2205782",
    description: "Place holder",
    image: "/placeholder.svg?height=300&width=300",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
  {
    name: "Shivansh Rastogi",
    roll_num: "2205851",
    description: "Place holder",
    image: "/placeholder.svg?height=300&width=300",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
  {
    name: "Tanishq Mowar",
    roll_num: "2205864",
    description: "Place holder",
    image: "/placeholder.svg?height=300&width=300",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
  {
    name: "Kumar Divyam",
    roll_num: "2205819",
    description: "Place holder",
    image: "/placeholder.svg?height=300&width=300",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
  {
    name: "Sriyans Kumar Panigrahi",
    roll_num: "22054189",
    description: "Place holder",
    image: "/placeholder.svg?height=300&width=300",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
  {
    name: "Soumya Ranjan Sahu",
    roll_num: "2205858",
    description: "Place holder",
    image: "/placeholder.svg?height=300&width=300",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
];
